# This is a basic workflow to help you get started with Actions

name: License Check

on:
  push:
    branches: [ master ]
    paths: 
      - .github/workflows/license.yml
      - .licensed.yml
      - package.json
      - package-lock.json
  pull_request:
    branches: [ master ]
    paths: 
      - .github/workflows/license.yml
      - .licensed.yml
      - package.json
      - package-lock.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up license checker
      uses: jonabc/setup-licensed@v1
      with:
        version: 2.x
        
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies in local env
      run: npm install
        
    - name: Run license check
      id: licensed 
      run: licensed status -c .licensed.yml

      
